import {
  Grid2Regular,
  CylinderRegular,
  Earth2Regular,
  Search2Regular,
  Settings4Regular,
  SunRegular,
  MoonRegular,
  ComputerRegular,
  PhotoAlbumRegular,
  Upload2Regular,
  Delete2Regular,
  CloseRegular,
  CheckRegular,
  ArrowLeftRegular,
  ArrowRightRegular,
  ArrowDownRegular,
  PicRegular,
  InformationRegular,
  FilterRegular,
  EyeRegular,
  EyeCloseRegular,
  Download2Regular,
  ShareForwardRegular,
  Refresh2Regular,
  StarRegular,
  LockRegular,
  AddRegular,
  More2Regular,
  TimeRegular,
  Camera2Regular,
  FileRegular,
  LayoutRightbarCloseRegular,
  FileExportRegular,
  ZoomInRegular,
  ZoomOutRegular,
} from '@mingcute/react/core-regular'

const icons = {
  grid: Grid2Regular,
  cylinder: CylinderRegular,
  sphere: Earth2Regular,
  search: Search2Regular,
  settings: Settings4Regular,
  sun: SunRegular,
  moon: MoonRegular,
  system: ComputerRegular,
  album: PhotoAlbumRegular,
  upload: Upload2Regular,
  trash: Delete2Regular,
  close: CloseRegular,
  check: CheckRegular,
  left: ArrowLeftRegular,
  right: ArrowRightRegular,
  down: ArrowDownRegular,
  photo: PicRegular,
  info: InformationRegular,
  filter: FilterRegular,
  eye: EyeRegular,
  hidden: EyeCloseRegular,
  download: Download2Regular,
  share: ShareForwardRegular,
  refresh: Refresh2Regular,
  star: StarRegular,
  lock: LockRegular,
  plus: AddRegular,
  more: More2Regular,
  time: TimeRegular,
  camera: Camera2Regular,
  file: FileRegular,
  panel: LayoutRightbarCloseRegular,
  export: FileExportRegular,
  zoomIn: ZoomInRegular,
  zoomOut: ZoomOutRegular,
}
export type IconName = keyof typeof icons
export function Icon({
  name,
  size = 20,
  className = '',
}: {
  name: IconName
  size?: number
  className?: string
}) {
  const Component = icons[name]
  return <Component size={size} className={className} aria-hidden="true" />
}
